# Name of the workflow as it will appear in the "Actions" tab.
name: Deploy Docs & Website

# This specifies that the workflow will run on every push to the 'main' branch.
on:
  push:
    branches:
      - main

# Defines the series of jobs to be run. We only have one job, 'deploy'.
jobs:
  deploy:
    # The type of machine to run the job on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest
    
    # The sequence of steps that make up the job.
    steps:
      # Step 1: Checks out your repository's code so the action can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Creates a './docs' directory and copies your custom homepage into it.
      # This is the staging area for the final website.
      - name: Copy Homepage to Docs
        run: mkdir ./docs && cp -r homepage/* ./docs/

      # Step 3: Installs Doxygen and Graphviz, which are needed to generate the API docs.
      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # Step 4: Runs Doxygen using your Doxyfile. 
      # The Doxyfile is configured to generate the API docs and place them in './docs/api'.
      - name: Generate Doxygen API Documentation
        run: doxygen Doxyfile

      # Step 5: Takes the entire contents of the './docs' folder (which now contains both
      # your homepage and the API docs) and pushes it to the 'gh-pages' branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
